# -*- coding: utf-8 -*-
#
# Copyright (C) 2024-2026 University of Münster.
#
# invenio-purge-expired is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.


[metadata]
name = invenio-purge-expired
version = attr: invenio_purge_expired.__version__
description = "A module containing the tasks for purging expired records."
long_description = file: README.rst, CHANGES.rst
keywords = invenio purge
license = MIT
author = University of Münster
author_email = forschungsdaten@uni-muenster.de
platforms = any
url = https://github.com/ulbmuenster/invenio-purge-expired
classifiers =
    Development Status :: 4 - Beta

[options]
include_package_data = True
packages = find:
python_requires = >=3.9
zip_safe = False
install_requires =
    invenio-base>=1.2.5
    invenio-drafts-resources>=5.1.0
    invenio-i18n>=2.1.1
    invenio-mail>=2.1.0,<3.0.0
    invenio-notifications>=0.4.0
    invenio-records>=2.0.0
    invenio-records-resources>=4.17.2
    invenio-search[opensearch2]>=2.1.0
    invenio-users-resources>=5.4.0
    arrow>=1.3.0

[options.extras_require]
tests =
    invenio-app>=1.3.4,<2.0.0
    pytest-invenio>=2.1.0,<3.0.0
    pytest-black>=0.3.0

[options.entry_points]
invenio_base.apps =
    invenio_purge_expired = invenio_purge_expired:InvenioPurgeExpired
invenio_celery.tasks =
    invenio_purge_expired = invenio_purge_expired.tasks


[bdist_wheel]
universal = 1

[pydocstyle]
add_ignore = D401

[isort]
profile=black

[check-manifest]
ignore =
    *-requirements.txt

[tool:pytest]
addopts = --black --isort --pydocstyle --cov=invenio_purge_expired --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml
testpaths = tests invenio_purge_expired
